### ISSUE TITLE
Configuration breaks when changing precondition temperature

### ISSUE THREAD

**Issue by DasBasti** [DasBasti/SmartHashtag#230]
## Version of the custom_component
0.6.2

## Describe the bug

> Ich habe den Smart frisch dem HA hinzugefügt, dann die Temperatur der Vorklimatisierung von 21°C auf 23°C konfiguriert, unmittelbar danach hat es die Anzeige auf dem Dashboard verdoppelt, und meine selbst konfigurierte rudimentäre Smart Ansicht zeigt nur noch Fehlermeldungen:

## Debug log
```text
2025-02-12 20:23:20.743 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smarthashtag' sets option flow config_entry explicitly, which is deprecated at custom_components/smarthashtag/config_flow.py, line 131: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/DasBasti/SmartHashtag/issues
2025-02-12 20:23:23.958 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smarthashtag' uses `async_config_entry_first_refresh`, which is only supported for coordinators with a config entry at custom_components/smarthashtag/__init__.py, line 41: await coordinator.async_config_entry_first_refresh(). This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/DasBasti/SmartHashtag/issues
2025-02-12 20:23:26.166 ERROR (MainThread) [custom_components.smarthashtag] Cannot access coordinator config: 'NoneType' object has no attribute 'entry_id'
```
https://www.smart-1-forum.de/forum/thread/336-smart-1-api-smart-home-integration/?postID=117977#post117977

**Comment by TomTomZoe** [comment]
Herzlichen Dank für die schnelle Lösung.
